# Site settings
title: Billy and Jessica
email: rsvp@billyandjessica.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.threathawk.com/" # the base hostname & protocol for your site

# User settings
twitter_username:
github_username:

# Build settings
markdown: kramdown
highlighter: rouge

# API settings
google_api_key: AIzaSyA2KaJ6Ld_C0HO0n2iEMMtvw09uWUX_Vuw
formbackend_key: htfokcha
