# Site settings
title: Billy and Jessica
email: billyandjessica@reawesome.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.threathawk.com/" # the base hostname & protocol for your site

# User settings
twitter_username:
github_username:
address: 17 Quat Quatta Ave 
  - line: Ripponlea VIC 3185

# Build settings
markdown: kramdown
highlighter: rouge

# API settings
google_api_key: AIzaSyAvYxeS7S1zvBZxFpRwwili5aF-xz8HPG4
