# Site settings
title: Billy and Jessica
email: billyandjessica@reawesome.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notbleh.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
highlighter: rouge
